% Autor:
% Data: 26/10/2019

progenitor(jose,ana).
progenitor(jose,joao).
progenitor(maria,ana).
progenitor(maria,joao).
progenitor(joao,mario).
progenitor(ana,helena).
progenitor(ana,joana).
progenitor(mario,carlos).
progenitor(helena,carlos).
sexo(jose,masculino).
sexo(joao,masculino).
sexo(mario,masculino).
sexo(carlos,masculino).
sexo(maria,feminino).
sexo(ana,feminino).
sexo(helena,feminino).
sexo(joana,feminino).
irma(ana,joao).
irma(helena,joana).
irma(joana,helena).
irmao(joao,ana).
mae(maria,joao).
mae(maria,ana).
mae(ana,helena).
mae(ana,joana).
mae(helena,carlos).
pai(jose,joao).
pai(jose,ana).
pai(joao,mario).
pai(mario,carlos).
avo(jose,maria).
avo(jose,helena).
avo(jose,joana).
avo(maria,maria).
avo(maria,helena).
avo(maria,joana).
avo(joao,carlos).
avo(ana,carlos).
tio(joao,helena).
tio(joao,joana).
tia(ana,mario).
tia(joana,carlos).
primo(mario,helena).
primo(mario,joana).
